name: release-please

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  package:
    name: Package and upload release archive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}

      - name: Build .pext
        run: ./build.sh

      - name: Upload archive to action
        uses: actions/upload-artifact@v4
        with:
          name: PlayniteLibraryServer
          path: PlayniteLibraryServer_*.pext
